routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/admin', 'AdminController@index')->name('admin');

Route::group(['prefix'=>'profile','as'=>'profile.'],function(){
    Route::get('/', 'ProfileController@index')->name('home');
//    Route::get('/posts', 'ProfileController@post');
    Route::post('/posts', 'ProfileController@savePost')->name('savePost');
});
Route::get('blog/{blog_uri}', ['uses' => 'BlogController@getPostsByBlog'])->name('blog_uri');
Route::get('lastActivity','BlogController@lastActivityOfBlogs')->name('lastActivity');

Route::get('blog/{blog_uri}/{post_id}', ['uses' => 'BlogController@getPostByID'])->name('blog_post');

Route::group(['prefix'=>'comment','as'=>'comment.'],function(){
    Route::post('/save', 'CommentController@saveComment')->name('saveComment');
});

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    //
    protected $table = 'comments';

    public function author()
    {
        return $this->belongsTo('App\User','author_id');
    }
    public function post()
    {
        return $this->belongsTo('App\Models\post');
    }
}

app/Models/Post.php
<?php

namespace App\Models;

use App\User;
use App\Models\Comment as Comment;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
    protected $table = 'posts';

    public function author()
    {
        return $this->belongsTo(User::class, 'author_id');
    }
    public function comments()
    {
        return $this->hasMany(Comment::class, 'post_id');
    }

    protected $guarded = ['id'];
}

app/Models/Profile.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\User as User;
class Profile extends Model
{
    //
    protected $table = 'profiles';

    public function role()
    {
        return $this->belongsTo(Role::class);
    }
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    //
    protected $table = 'roles';

    public function profiles()
    {
        return $this->hasMany(Profile::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Models\Profile as Profile;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function profile()
    {
        return $this->hasOne(Profile::class);
    }

    public function posts()
    {
        return $this->hasMany('App\Models\Post', 'author_id');
    }

    public function comments()
    {
        return $this->hasMany('App\Models\Comment', 'author_id');
    }
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AdminController extends Controller
{
    //
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        return view('home');
    }

}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use App\Models\Profile as Profile;
use App\Models\Post as Post;
use Auth;
class BlogController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');

    }

    public function getPostsByBlog($blog_uri)
    {

        $blog = Profile::where('blog_uri', $blog_uri)->first();

        if ($blog) {
            $posts = Post::with('comments')
                ->where('author_id', $blog->user_id)->take(10)->get();

            return view('blog.blogPosts', [
                'header' => 'مطالب '.$blog->blog_bio,
                'posts' => $posts
            ]);
        } else {
            abort(404);
        }
//        return view('post.create');
    }

    public function lastActivityOfBlogs()
    {
        $posts = Post::with('comments','comments.author','author','author.profile')->latest()->take(2)->get();

        $user = User::with('profile')->where('id',Auth::user()->id)->first();
        return view('blog.lastActivity', [
            'header' => 'آخرین مطالب وبلاگ ها',
            'posts' => $posts,
            'user'=>$user
        ]);
    }

    public function getPostByID($blog_uri,$post_id)
    {
        $post = Post::with('author','author.profile')->where('id', $post_id)->first();
        if($post->author->profile->blog_uri==$blog_uri){
            return view('blog.blogPost', [
                'header' => $post->title,
                'post' => $post
            ]);
        }
        else
            abort(404);
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Comment as Comment;
use App\User;
use Auth;
class CommentController extends Controller
{
    //
    public function saveComment()
    {
        $request = request();

        $user = User::with('profile')->where('id',Auth::user()->id)->first();

        $comment = new Comment;
        $comment->text = $request->input('text');
        $comment->author()->associate(auth()->user()->id);
        $comment->post()->associate( $request->input('post_id'));
        $comment->save();
        return view('post.create', [
            'message' => 'با موفقیت ثبت شد',
            'user' => $user
        ]);
        return redirect()->back()->with('success', 'Data saved successfully!');

    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
//        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use Faker\Provider\DateTime;
use Illuminate\Http\Request;
use App\Models\Post as Post;
use App\User;
use Auth;

class ProfileController extends Controller
{
    //
    public function __construct()
    {
        $this->middleware('auth');

    }

    public function index()
    {
        $user = User::with('profile')->where('id',Auth::user()->id)->first();


        return view('post.create', ['user' => $user]);
    }

    public function savePost()
    {
        $request = request();
        // with array & create method
//        $now=DateTime::dateTime();
//        $user_data=[
//            'title'=>$request->input('title'),
//            'description'=>$request->input('description'),
//            'content'=>$request->input('content'),
//            'author_id'=>auth()->user()->id,
//            'publish_date'=>new \DateTime(),
//            'is_enabled'=>1,
//            'comment_count'=>0,
//        ];
//        Post::create($user_data);

        $user = User::with('profile')->where('id',Auth::user()->id)->first();
        $post = new Post;
        $post->title = $request->input('title');
        $post->description = $request->input('description');
        $post->content = $request->input('content');
        $post->author()->associate(auth()->user()->id);
        $post->save();
        return view('post.create', [
            'message' => 'با موفقیت ثبت شد',
            'user' => $user
        ]);

    }
}

resources/views/blog/blogPost.blade.php
<!DOCTYPE html>

<html lang="fa">
<head>
    <link href="{{asset('css/styles.css')}}" rel="stylesheet">
    <link href="{{asset('css/style.bundle.rtl.css')}}" rel="stylesheet">

    <link href="{{asset('css/customFont.css')}}" rel="stylesheet">
    <title>{{ $post->title }}</title>
</head>

<body data-page-name="home" class="body-home" data-login="false" data-app="production">


<noscript>
    <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5GS688K" height="0" width="0"
            class="page_speed_970244490"></iframe>
</noscript>


<section class="site-body">

    <div class="alert"></div>
    <div class="notify-msg"></div>

    <main id="app" class="site-main">
        <section class="page-inner">
            <section style='text-align:center;'>

                @if (isset($header) && $header)
                    <h1>{{$header}}</h1>
                @endif
            </section>

            <section class="page-content">
                <section class="page page-home page-">
                    <section class="poststream container">

                        <section class="poststream-inner">

                            <div class="poststream-content">


                                <div class="post-stream infinite-container">
                                    <div class="jscroll-inner">


                                        @if (isset($post) && $post)
                                            <article class="card card-post js-button-action">
                                                <header class="post-meta" data-user-id="gmlu1apiyj8q">
                                                    <div class="postStream-author popover-box js-popover"
                                                         data-user-hash="gmlu1apiyj8q">
                                                        <div class="meta--avatar js-popover-append">
                                                            <a href="{{route('blog_uri', [$post->author->profile->blog_uri])}}"
                                                               dideo-checked="true">
                                                                <img src="{{asset('img/default-avatar.jpg')}}"
                                                                     alt="post">
                                                            </a>
                                                        </div>
                                                        <div class="meta--author">
                                                            <a class="link name "
                                                               href="{{route('blog_uri', [$post->author->profile->blog_uri])}}"
                                                               dideo-checked="true">{{$post->author->name}}</a>
                                                            <div class="meta--time">
                                                                {{$post->publish_date}}
                                                            </div>
                                                        </div>
                                                    </div>
                                                </header>
                                                <div class="post-content">

                                                    <h2 class="post--title">{{ $post->title }}</h2>
                                                    <div class="post--text">
                                                        {!! $post->content !!}
                                                    </div>

                                                </div>
                                                <hr>
                                                <footer class="">

                                                    @if (isset($post->comments) && $post->comments)
                                                        @foreach ($post->comments as $comment)
                                                            <div>
                                                                <div class="post-action-buttons">
                                                                    <svg class="icon svg stroke" width="21px"
                                                                         height="21px" viewBox="25 7 18 18"
                                                                         version="1.1"
                                                                         xmlns="http://www.w3.org/2000/svg"
                                                                         xmlns:xlink="http://www.w3.org/1999/xlink">
                                                                        <path
                                                                            d="M35.6875,7 L32.3125,7 C28.27375,7 25,10.27375 25,14.3125 C25,16.92925 26.3854375,19.2079375 28.4520625,20.5 L28.375,20.5 L28.375,25 L33.4375,21.625 L35.6875,21.625 C39.72625,21.625 43,18.35125 43,14.3125 C43,10.27375 39.72625,7 35.6875,7 Z M35.7750243,19.5499022 L33.4083577,19.5499022 L30.4500244,21.3249022 L30.4500244,19.2238939 C28.3862911,18.4902272 26.9000244,16.5395022 26.9000244,14.2249023 C26.9000244,11.2837273 29.2838494,8.89990234 32.2250243,8.89990234 L35.7750243,8.89990234 C38.7161993,8.89990234 41.1000242,11.2837273 41.1000242,14.2249023 C41.1000242,17.1660772 38.7161993,19.5499022 35.7750243,19.5499022 Z"></path>
                                                                    </svg>
                                                                </div>

                                                                <p>{{ $comment->author->name }} گفت: </p>
                                                                <p>{!! $post->content !!} </p>
                                                            </div>
                                                            <br>
                                                        @endforeach
                                                    @endif
                                                        @include('post.comment')
                                                </footer>
                                            </article>

                                        @else
                                            <article class="card card-post js-button-action">
                                                <div class="post-content">
                                                    <p>مطلبی جهت نمایش وجود ندارد</p>
                                                </div>
                                            </article>

                                        @endif


                                    </div>
                                </div>
                            </div>
                        </section>
                    </section>
                </section>
            </section>
        </section>
    </main>

</section>
</body>

</html>

resources/views/blog/blogPosts.blade.php
<!DOCTYPE html>

<html lang="fa">
<head>
    <link href="{{asset('css/styles.css')}}" rel="stylesheet">
    <link href="{{asset('css/customFont.css')}}" rel="stylesheet">
    @if (isset($header) && $header)
        <title>{{$header}}</title>
    @endif
</head>

<body data-page-name="home" class="body-home" data-login="false" data-app="production">


<noscript>
    <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5GS688K" height="0" width="0"
            class="page_speed_970244490"></iframe>
</noscript>


<section class="site-body">

    <div class="alert"></div>
    <div class="notify-msg"></div>

    <main id="app" class="site-main">
        <section class="page-inner">
            <section style='text-align:center;'>

                @if (isset($header) && $header)
                    <h1>{{$header}}</h1>
                @endif
            </section>

            <section class="page-content">
                <section class="page page-home page-">
                    <section class="poststream container">

                        <section class="poststream-inner">

                            <div class="poststream-content">


                                <div class="post-stream infinite-container">
                                    <div class="jscroll-inner">


                                        @if (isset($posts) && $posts)
                                            @foreach ($posts as $post)
                                                <article class="card card-post js-button-action">
                                                    <header class="post-meta" data-user-id="gmlu1apiyj8q">
                                                        <div class="postStream-author popover-box js-popover"
                                                             data-user-hash="gmlu1apiyj8q">
                                                            <div class="meta--avatar js-popover-append">
                                                                <a href="{{route('blog_uri', [$post->author->profile->blog_uri])}}"
                                                                   dideo-checked="true">
                                                                    <img src="{{asset('img/default-avatar.jpg')}}"
                                                                         alt="post">
                                                                </a>
                                                            </div>
                                                            <div class="meta--author">
                                                                <a class="link name "
                                                                   href="{{route('blog_uri', [$post->author->profile->blog_uri])}}"
                                                                   dideo-checked="true">{{$post->author->name}}</a>
                                                                <div class="meta--time">
                                                                    {{$post->publish_date}}
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </header>
                                                    <div class="post-content">
                                                        <a href="{{route('blog_post', [$post->author->profile->blog_uri,$post->id])}}"
                                                           dideo-checked="true">
                                                            <h2 class="post--title">{{ $post->title }}</h2>
                                                            <div class="post--text">
                                                                {!! $post->content !!}
                                                            </div>
                                                        </a>
                                                    </div>
                                                    <hr>
                                                    <footer class="">

                                                        @if (isset($post->comments) && $post->comments)
                                                            @foreach ($post->comments as $comment)
                                                                <div>
                                                                    <div class="post-action-buttons">
                                                                        <svg class="icon svg stroke" width="21px" height="21px" viewBox="25 7 18 18" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                                                                            <path d="M35.6875,7 L32.3125,7 C28.27375,7 25,10.27375 25,14.3125 C25,16.92925 26.3854375,19.2079375 28.4520625,20.5 L28.375,20.5 L28.375,25 L33.4375,21.625 L35.6875,21.625 C39.72625,21.625 43,18.35125 43,14.3125 C43,10.27375 39.72625,7 35.6875,7 Z M35.7750243,19.5499022 L33.4083577,19.5499022 L30.4500244,21.3249022 L30.4500244,19.2238939 C28.3862911,18.4902272 26.9000244,16.5395022 26.9000244,14.2249023 C26.9000244,11.2837273 29.2838494,8.89990234 32.2250243,8.89990234 L35.7750243,8.89990234 C38.7161993,8.89990234 41.1000242,11.2837273 41.1000242,14.2249023 C41.1000242,17.1660772 38.7161993,19.5499022 35.7750243,19.5499022 Z"></path>
                                                                        </svg>
                                                                    </div>

                                                                    <p>{{ $comment->author->name }} گفت: </p>
                                                                    <p>{!! $post->content !!} </p>
                                                                </div>
                                                                <br>
                                                            @endforeach
                                                        @endif
                                                    </footer>
                                                </article>

                                            @endforeach
                                        @else
                                            <article class="card card-post js-button-action">
                                                <div class="post-content">
                                                   <p>مطلبی جهت نمایش وجود ندارد</p>
                                                </div>
                                            </article>

                                        @endif


                                    </div>
                                </div>
                            </div>
                        </section>
                    </section>
                </section>
            </section>
        </section>
    </main>

</section>
</body>

</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/admin.blade.php
<!DOCTYPE html>


<html lang="en" direction="rtl" style="direction: rtl;">

<!-- begin::Head -->
<head>

    <!--begin::Base Path (base relative path for assets of this page) -->
    <base href="../">

    <!--end::Base Path -->
    <meta charset="utf-8"/>
    <title>پروفایل کاربری</title>
    <meta name="description" content="Latest updates and statistic charts">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{{asset('css/customFont.css')}}">
    <link rel="stylesheet" href="{{asset('css/style.bundle.rtl.css')}}">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
</head>

<!-- end::Head -->

<!-- begin::Body -->
<body class="body-pannel">
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">

    <div class="row">
        <div class="col-md-4">
            <!-- begin:: Aside Menu -->
            <div class="kt-aside-menu-wrapper kt-grid__item kt-grid__item--fluid" id="kt_aside_menu_wrapper">
                <div id="kt_aside_menu" class="kt-aside-menu " data-ktmenu-vertical="1" data-ktmenu-scroll="1">
                    <ul class="kt-menu__nav ">
                        <li class="kt-menu__section kt-menu__section--first">
                            <h4 class="kt-menu__section-text">{{$user->name}}</h4>
                            <i class="kt-menu__section-icon flaticon-more-v2"></i>
                        </li>

                        <li class="kt-menu__item " aria-haspopup="true"><a href="{{route('profile.home')}}" class="kt-menu__link "><i class="kt-menu__link-icon flaticon-share"></i><span class="kt-menu__link-text">ایجاد مطلب</span></a></li>
                        <li class="kt-menu__item " aria-haspopup="true"><a href="{{route('blog_uri',$user->profile->blog_uri)}}" class="kt-menu__link "><i class="kt-menu__link-icon flaticon-suitcase"></i><span class="kt-menu__link-text">نمایش بلاگ شخصی</span></a></li>
                        <li class="kt-menu__item " aria-haspopup="true"><a href="{{route('lastActivity')}}" class="kt-menu__link "><i class="kt-menu__link-icon flaticon-light"></i><span class="kt-menu__link-text">لیست 10 پست آخر وبسایت</span></a></li>
                        <li class="kt-menu__item " aria-haspopup="true"><a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" class="kt-menu__link "><i class="kt-menu__link-icon flaticon-light"></i><span class="kt-menu__link-text">خروج</span></a></li>
                         </ul>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </div>

            <!-- end:: Aside Menu -->
        </div>
        <div class="col-md-6">
            @yield('content')
        </div>
    </div>

</div>
</body>

<!-- end::Body -->
</html>

resources/views/post/comment.blade.php
<h1>ثبت کامنت</h1>
        <div class="col-md-12">
            @if (isset($message) && $message)
                <div class="alert alert-success">{{$message}}</div>
            @endif
            <form action="{{ route('comment.saveComment') }}" method="POST">
                {{csrf_field()}}
                <input hidden type="text" name="post_id" value="{{$post->id}}">
                <div class="form-group">
                <label for="content">متن</label>
                    <input type="text" class="form-control" name="text" id="">
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-success" name="submit_save_user" value="ذخیره اطلاعات">
                </div>
            </form>
        </div>

resources/views/post/create.blade.php
@extends('layouts.admin')
@section('content')
    <div class="flex-right position-ref full-height">
        <div class="container">
            <div class="row">
                @include('post.form')
            </div>
        </div>
    </div>
@endsection

resources/views/post/form.blade.php
<script src="{{asset('ckeditor/ckeditor.js')}}"></script>
<h1>ثبت مطلب</h1>
        <div class="col-md-12">
            @if (isset($message) && $message)
                <div class="alert alert-success">{{$message}}</div>
            @endif
            <form action="{{ route('profile.savePost') }}" method="POST">
                {{csrf_field()}}
                <div class="form-group">
                    <label for="title">عنوان</label>
                    <input type="text" class="form-control" name="title" id="">
                </div>
                <div class="form-group">
                    <label for="description">خلاصه</label>
                    <input type="text" class="form-control" name="description" id="">
                </div>
                <div class="form-group">
                <label for="content">متن</label>
                <textarea name="content" class="form-control" id="editor1" cols="30" rows="10"></textarea>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-success" name="submit_save_user" value="ذخیره اطلاعات">
                </div>
            </form>
        </div>
        <script>
            // Replace the <textarea id="editor1"> with a CKEditor
            // instance, using default configuration.
            CKEDITOR.replace( 'editor1');
            CKEDITOR.config.contentsLangDirection = 'rtl';
            CKEDITOR.config.extraPlugins = 'uploadfile';
        </script>